apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-frontend
  namespace: fintrack
  labels:
    app: fintrack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintrack-frontend
  template:
    metadata:
      labels:
        app: fintrack-frontend
    spec:
      containers:
        - name: frontend
          image: 203637463799.dkr.ecr.us-east-1.amazonaws.com/fintrack-frontend:115a2d3f15f8eb7fc8f2a20c1037ad7747e4b2e7
          ports:
            - containerPort: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"