apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack-ingress
  namespace: fintrack
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - fintrack.qossim005.online
      secretName: fintrack-tls
  rules:
    - host: fintrack.qossim005.online
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: fintrack-backend
                port:
                  number: 3001
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: fintrack-frontend
                port:
                  number: 80