apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-backend
  namespace: fintrack
  labels:
    app: fintrack-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fintrack-backend
  template:
    metadata:
      labels:
        app: fintrack-backend
    spec:
      serviceAccountName: fintrack-backend

      containers:
        - name: backend
          image: 560205084952.dkr.ecr.us-east-1.amazonaws.com/fintrack-backend:c5c0c2c9cfb5cf29f17cad6d24bfc4cee1c8bd34
          ports:
            - containerPort: 3001

          env:
            - name: PORT
              value: "3001"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_S3_BUCKET_NAME
              value: "fintrack-dev-receipts-560205084952"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fintrack-backend-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fintrack-backend-secrets
                  key: JWT_SECRET

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"