---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fintrack-backend-secrets
  namespace: fintrack
spec:
  encryptedData:
    DATABASE_URL: AgAB67xcAMPXpFFMjBoew0NcNWr8kCQnrbdfuvVVV3KDHFI/BkeIK6TNiy2ZtbGk/Uwi7mIimMhjqAZpyX2jd5K768H58RNOLGPh3XMV0pbwHn+VyIw/BfvHsB5FcDZp//A6lSqhMkpB/kkW9HRXEzkILn+xwR4+w8S8nqitpiPntAFWYwZ4wvReSTP9r1xqq4RnoNtb77mPDnFN7WaWVu5Fkb3b7NVCm109so4T4FrkMrxnIBVb8fHwA9N8CrVQ6tb4x9/9PWJP1VjTMyyD0Ax4J2HCCb0p+bnrWAYRPDsn1SVCBS4Ka6EeS6MA25O+Ew93qOPLZNE8ejNHkoEYdGAOTclyz5fYgKxd3V1xgedkksrKWZ1Lz8wuA7ZiBgJ5E28Zu0M/xwNtHNWX1uYOZQp9CICxqw14lQ7tFw7QIMaRN/lLwEyFGF+EcJQIAe7ONXNR6ceEVof1ei3yMHXGwBJaiwC0qlsd5eI44gKmY/MgI2mb/I1eT092QC/DdDs1yyMPlwd9/ojbIntdTuQ3obS2wXY/EVzk/SXk7U2iDfkSC6MDWbCaoo+lLncThyvg4Dzz8zR/FLq/LN4FFptBHd6Hl2ZnyO92A4rfejSebBp8hxh2uAiym6eS6l7Y/mdu9c/aOfKIb3i4p4qUWmIPs/HWaZjdKU8ZmRXPjcktkJGY+Dw+uF/tWiWd9AFDxsp1ya16q5BdIWNPCgxCX1QMqjleq29vytgfEkhz47d3UfYbwz5+8I5A826jgOSxFn0ibFdd8zIKgHhFRb3E1sfzZ5NRZVX8t7K4MUOId0yIbLIPMOBgD+iRpABWnb6tV3vIJre7OmqIyerzoHJ4MUx3/cuMDvHzGvZ6JA==
    JWT_SECRET: AgAuRvVIhwxHYLxVwkJMmXh6wkSXiIoDXDf/0jnpsmyOgBlrcQl64yxRmD50uZ3gW8XDKFCe/BXNjBkJIXyNFjIiL/g29cVJoK+rwgjSDMijMoQsi+9Gv5BjkAZRr0nH3mgZUYvdmOwBRhUx3wCZoFPWvlaVuUS1jZQeLsB0PteRzhtMLn8z62Y5VmWByaXoQQcBJFyWiqUL7QW9wUZ8BvBo7QZekWItMFs/UMLYjwcP+NHVJnxKHBfmT2FOCTlDRsZrzZM8IPcHI7iVnA8VakGKzr1GHXPaeXmsqY83lgIM7vg3IUHHMNS3ORTaj7huP3Wv2Vrb3aT5XbYHG7ViwizzOYcydAYQ/SFgm9w34ss0nIg3zm7ZjrXCmplj/jv67e+Zh2xcTfLMADDTEfFlVPv6y6ahWUh9JbhvvHH5xbg1uOgG73eT1L6fiITGnrvaWyq2UveuKuhF81MUBiq0JN66aF6ynG98Q09w+TJD+34/afqb5gusHLy/kGTqmky/qb4i1mRl6TnjTGrP8c0IzNE4qBvcbMOFVYtmT3SPLGxSfJCmrLo5f7yhvPadrHQrkpzZH8G2YA8ua7lya2uiDDXSJ2Fyzs7CoQSacnmDSpBOHamN1h0w7DR13FzoY6fk+SWkwpUAjxQdWKmmmDhD/zrhLT6P3R9NRBkWmp5B2HggOOlUl2zMcwpmWabjysjm4Mt+Lnhp9zor1fPdWdwY+bDyMC6HpzI+vFluz0GfmaaFtsbVHITsztsf40S+Db8BmicrsRI=
  template:
    metadata:
      creationTimestamp: null
      name: fintrack-backend-secrets
      namespace: fintrack
    type: Opaque
