---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fintrack-backend-secrets
  namespace: fintrack
spec:
  encryptedData:
    DATABASE_URL: AgArPMJcDtjdEtK96Y0c+8ZDvTVMtMCofBvKnwtlq0Ov8DFc9Uiwi2sJciiMKmVozE2DhAw+la30qkqZTTNDxH7cyNjTiOwpX1+xEKnVeDOTd4Ug831RYhqsMPiL+fK3bT5eayI6ID8OJbM0EE4DdI6UJN5ITJ5CMXfWd4/4+BFSZzyhqYFoaewq+jhEeGtRhfNJYplrUa4CnAytRGRJyBf3cpjCmbCYPJbL6v8na1gvu7KT5jVlmmwOp6LRqN5UmzzRRllkKEIuJ6WV4bg+LFIL0Vx15sXEGQRGuVyX9SXGcGDBQa1CHI/rkeWfks4qE1aHDBvOjn9HLNWb83BsjB7RBfrcwiPmNLYJdcs8ve7W3T+D8CwCBMbgHuP4yN27lDmtfMNu3VF7F4q9gTKFnl/qgzOWVsbMXlN+LfPmdeN126opavJfve0bNuaCdhmfufBti/KAnB2VT0mo+w/az7OT++qTS55WrvdIuEOV3tIBt+0Va3F5oyvMJSKpsO/ZRORT7VLNAg+KmkxguXe+Ypek1fnUWbPtBDdOWcNeln8p0Mk3DSPlCA4M2Rn3HZuZrKCkM74yX14I95/t8r9J6zHc5MVdtZg1+XSMndkhPppIdxGqiK0b/TD598VKyv2iQLcOHM/AnP1cq4VihUCa6EmbrSTDckng/0NXdmIfzLGMRkGIMSNM6zf+hVgLkJXoCEbZdlrgbywz8YAVe4uf7gpKI/0t9z9CzuFCLTSzfrMG05x/+m/1zLFwvmyDjPe/jS0myzd9pel54kb/dgXmmctLvkyhiFo0ioFfVawR+oGXHBG85L/0rJ9Yu4OEuh5K9L+/RjAKFdWu7B61fnWzjshJA4md4U9vzQ==
    JWT_SECRET: AgAkfGussQZK3Ks0r+GNgnfPfAZwy6iwGWK/f+euFXcdSQVqSZHgcjiifVmyPbfpwWvVFXa62ikWwcdfJXcNyLIn7TZoZJFQjqMt4crtWrFoPxrn/OF69W+74hDe3fFYRc2OjVLfRcUorXunfN68oh+Yy1T+ekea83poMWo0N+JnU/ucHhGtfw2y3DBnpW1lAUWy0LqW3VibAdSzQLH1blaKIRIwk0MJIdFrgJNLZAZ7ceXEYLxi6M7gfuNjbATNlxGlRmQh9tMIsgr34g9hfncjSkdX4P0TQqUutYw0/o434G9d+0Mmlw8aLq1JVhNaJMf1QbMy5pXfQiNi7mfBpbDa2CwZ+7HowTX1P7/zXoFs53txOY8s6W3ubRr8MfaIgMqlAhna8UJ0pncocDzRepjjPqWuyY59NtBXojRvhLDfVKgAmeropbACsZSC0kBldnW9V2ZBAEuCfHjU54F6KaP5GhxFRM/Wl6QSvg3OJmushLN3SZ0Tvgd/yy7jRP/AgJeLLAA5jeApBYs829BlPouJ6/OgPTemTwBdibQrCQXhT8HpsOpGuFgGV22OmYvuCV1eBNgCIhB753k9nHV8ZV+dYaY87yZa9o5xCWEBYi5wyAFQCSx9aEcxWUCtNI0wbuZZlF77mFgja0QnqWyEP9eFEBo75HgXkuZlX0ZZuD+vgs45/tYUATHTa149ipaK5NZ0SuC/3CXVVGjOzu0oV+ZQrz9KtF8wQi8yfQ==
  template:
    metadata:
      creationTimestamp: null
      name: fintrack-backend-secrets
      namespace: fintrack
    type: Opaque
