---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fintrack-backend-secrets
  namespace: fintrack
spec:
  encryptedData:
    DATABASE_URL: AgA2Si+ueJ2iTdy/Ml20NUl3ydox7vTVI1D8S6y/LkhnT4H8DAVt0Zdt5h5IRi6D94GK74TUuYt+06/5R8VI9i0Z+TgpkB9e4u4u1Lr80i1aJ/8gfU4fRE3cxyW+uVFjmGTVVvOpv75xuiylmdagRHEI2Vxnge5BQVVS958CknQTXa5i2jduLPpXyIKjofl8w/+tUTwbVoVf5QUeoB2wScy8T2sw6gJk4Wl06LN1E5flQWKNi+OCy9Z1ESp0yJWnKYrVfLL/y3Cdrvb9SEqfObG5mEC1wuu2rhQ7o5oB2wGYgstLyF7Ltnv6TW3k+jvxD9xWmbOxstX9RE+Okxoxo7+bEBO+8BD7ilYaxi9TApvv5gFwauWrL1+kawTV6vxMgOlky1L4rs5ECm2F+PMA3J28rMco1u89bp7jmmI77i4guuPKfGGLIVMHSjIMNiMb04PpGWZRR0rxXmUknw3+0vnlMKxUwe8wpbSZ6v5TLS/PETo0+bg2T+Uv8l4SZ+xyvtE7b00SCKVi8z1o/s43tX99UxTF2WVQ/vYgdc9YxyWiHcm0g/1UAi3ePLO9cVWGYbOl3g0+NIb6ia4NZysV/wwGn/evk9NpSgnNdS7EAOHHwTgyLckq/FTTVOoz8/YjPtT1l+xmBpTWVOp9fSRX9NKCj05iR55wZYjlAfWDTFiek+dHB0imhIAOUTmqVpx0MQCgINSaZWXxfUQsFk1ORID9swPs+kAyaTrMVCA+ueeATFHLl2l+I619l87PnxY2177l7Lb/H8KGD9q2DE0x1u1eLMCa3dQAROCu7diO9oyGGJUUoT668cAQmQBX91IeWF9CfdChUMVkilNwt7icEI/6ecI5hH7f0A==
    JWT_SECRET: AgC8SFrpq1p0Ng+f0EZ5qx4xxlMVPk/iK1m+aGj7vOYPz65S4rTcOU7UkgRx9TPG7WqJeCUiUS/NidRDn8pjZZWTYuEP0JlBYbtOliMffuHbMTAPeKGX7uapd9fGKyMveNZ0iabOHwSGfUF37NQ2dClSDXbv5yDPr5t5Q9FTTM6llkNMcIU2R5969N9PTOLOF0pAWKQXnzGCL7ztSOzxb02w6jC83jG1MHD7ExGnT2jZx/NLXhlcziKhwQ+VG3uZoX3FIZjXjPlXU18ts9u3R6QdVj3rjGkOZwifUBgUz3YtYIaYGrYHMHOUJhGZ7+sRP2ueUnXhhoYhjdcICEFzBIUwQ+tXvL+uZNs5+j09wfUACyB+6oFHPpbcebBQnMlrpMpNWS+3EUnai5O5N51oKL2vlQKjkLjtn+P77jp/QpaqM70q2ZPuoMfqE5bGKX2ox9kYmQ+FgzwIYETockVXIdXYasxTdeZDl0LFfQ9/gSg8yFOPR96jlyw31ZYb51tZ6SPwsKRDqBSaOqTdFN9rTMrEf0UnQcnQhHJxL8VlA3hJOv2leAzsNq8QpE2c9nfaIGlF4BX9jHk4FfudDHdTjPYBLbwz2FU1zJMh3Dv84qWoihBLqoyXAbpixGvtzWbZ2CC58M5Ozq9+3vO9SN5Z+15LqWZISOmWKKDW1paqh0swFYOlZjNKNhEzyVSkYtYDeE1hZ99l9lCBgfTlQdoc+2e2DlUCW+VlaIKsydjnDdloHRyVJjiNa/7Br6To2lFa2vMZ0tw=
  template:
    metadata:
      creationTimestamp: null
      name: fintrack-backend-secrets
      namespace: fintrack
    type: Opaque
