apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintrack-backend
  namespace: fintrack
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::560205084952:role/fintrack-dev-backend-role"